apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontrfc-deployment
  labels:
    app: frontrfc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontrfc
  template:
    metadata:
      labels:
        app: frontrfc
    spec:
      containers:
        - name: frontrfc
          image: nourchenacr.azurecr.io/frontendrfc:v1 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontrfc-service
spec:
  type: LoadBalancer
  selector:
    app: frontrfc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80