apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontrfc-deployment
  labels:
    app: frontrfc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontrfc
  template:
    metadata:
      labels:
        app: frontrfc
    spec:
      containers:
        - name: frontrfc
          image: nourchenh/frontrfc:6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontrfc-service
spec:
  type: LoadBalancer
  selector:
    app: frontrfc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontrfc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.hedfidevops.com  # Remplacez par le nom de domaine de votre choix
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontrfc-service
                port:
                  number: 80